### ISSUE TITLE
Appears to check duplicates only on filename, not on any kind of hashing

### ISSUE THREAD

**Issue by Aeristoka** [jegasus/world-manager#2] opened 2021-04-04 16:25 UTC
This appears to cause duplicative file names (even in different directories) to get cleared out after the first one is processed.

**Comment by jegasus** [comment] 2021-04-04 18:53
Hi there! Thanks for checking the tool out! 
Can you please be a bit more descriptive with your problem? For example, what images existed before and what existed existed after you ran the tool?
Also, the code actually does check file hashes for duplicates, not filenames. In fact, the code doesn't do ANY kind of filename checking. 
Could you also please send some screenshots of what you tried and what happened next?
Thanks again for the feedback =)

**Comment by Aeristoka** [comment] 2021-04-04 22:37
In example here, a single folder that was worked on:
Original:
![image](https://user-images.githubusercontent.com/7988297/113523258-f20a6300-9563-11eb-901d-8770a9ed4505.png)

Worked on:
![image](https://user-images.githubusercontent.com/7988297/113523264-fafb3480-9563-11eb-8f3b-6639e970bf5d.png)

Worked on _trash:
![image](https://user-images.githubusercontent.com/7988297/113523269-0b131400-9564-11eb-8ae3-b3460f75febd.png)

**Comment by Aeristoka** [comment] 2021-04-04 22:41
My guess about file name checking was based on this:
![image](https://user-images.githubusercontent.com/7988297/113523332-87a5f280-9564-11eb-9819-9432aabb2938.png)

![image](https://user-images.githubusercontent.com/7988297/113523337-8d9bd380-9564-11eb-8259-e2a1698c0c56.png)

All files represented in that one scene.

Next scene:
![image](https://user-images.githubusercontent.com/7988297/113523353-9f7d7680-9564-11eb-919c-9fb95f7fec24.png)

![image](https://user-images.githubusercontent.com/7988297/113523358-a99f7500-9564-11eb-86c8-a909716665d8.png)

**Comment by jegasus** [comment] 2021-04-07 03:35
Thanks for the extra info. 
This seems to be a duplicate of #6 . 
I'm marking this as a bug and currently investigating why this is happening.

**Comment by jegasus** [comment] 2021-04-07 05:11
I've fixed the issue in [release 0.0.2](https://github.com/jegasus/world-manager/releases/tag/0.0.2)! The problem was in the function that fixes image files' extensions (for example, from `PNG` to `JPEG`). 
I'm closing the issue. 
If the problem persists, please feel free to re-open it!

**Closed as completed by jegasus** 2021-04-07 05:11 UTC
Labels: bug, duplicate

**Comment by Aeristoka** [comment] 2021-04-07 13:36
I am super excited to test this 0.0.2 release! 😄

**Comment by Aeristoka** [comment] 2021-04-07 15:41
Another example R20Exporter/R20Converter world as in #6 👍 
![image](https://user-images.githubusercontent.com/7988297/113894601-6839e000-9785-11eb-983b-cba66dfc52c4.png)

Insanely good results!
